# Eureka service client with support of Ribbon, Feign and Hystrix.

spring:
  application:
    name: spring-cloud-eureka-service-client
  sleuth:
    sampler:
      probability: 1.0

server:
  port: 9001

eureka:
  client:
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

feign:
  hystrix:
    enabled: true
