spring:
  application:
    name: spring-cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: baidu
          uri: https://www.baidu.com/
          predicates:
            - Path=/baidu/**
        - id: service_provider
          uri: lb://spring-cloud-eureka-service-provider
          predicates:
            - Path=/service-provider/**
          filters:
            - StripPrefix=2
            - AddResponseHeader=X-Response-Hello, Wolrd
        - id: hystrix_route
          uri: lb://spring-cloud-eureka-service-provider
          predicates:
            - Path=/hystrix-route/**
          filters:
            - StripPrefix=1
            - name: Hystrix
              args:
                name: fallbackcmd
                fallbackUri: forward:/fallback
        - id: retry_test
          uri: lb://spring-cloud-eureka-service-provider
          predicates:
            - Path=/retry
          filters:
            - StripPrefix=1
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY

server:
  port: 9000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.cloud.gateway: debug

management:
  endpoints:
    web:
      exposure:
        include: "*"
