spring:
  application:
    name: spring-cloud-eureka-service-provider
  sleuth:
    sampler:
      probability: 1.0
      
server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
