spring:
  application:
    name: spring-cloud-config-client

  cloud:
    bus:
      enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8002

management:
  endpoints:
    web:
      exposure:
        include: "*"

